name: Bug Report
description: There is something broken with the website
body:
  - type: markdown
    attributes:
      value: |
        Please be as detailed as possible so that I can attempt to fix the issue.

  - type: textarea
    id: environment
    attributes:
      label: What happened?
      description: |
        Please tell me what happened that made you decide to come leave a bug report for the parish website.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        Please describe the expected behavior and the actual result you got.
      placeholder: >
        What is it you expected to happen? This should be a description of how the
        functionality you tried to use is supposed to work.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the behavior
      description: |
        Describe the steps you took for this problem to come up. Such as: you clicked a link on the information page and it did nothing.

        Screenshots can also be included if they help illustrate a behavior.
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Other
      description: |
        Please provide any other information that would help me know what you're talking about.
    validations:
      required: false