name: Suggestion
description: Found a typo or something that needs updating?
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to open an issue and help make the site better.

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: |
        Why should we update the page?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: |
        What should we do instead?
    validations:
      required: true
